application: replaylivetweet
version: 1-1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /app/.*
  script: main.app

- url: /
  static_files: html/index.html
  upload: html/index\.html

- url: /blank\.html
  static_files: html/blank.html
  upload: html/blank\.html

- url: /css
  static_dir: html/css

- url: /data
  static_dir: html/data

- url: /images
  static_dir: html/images

- url: /js
  static_dir: html/js

- url: /template
  static_dir: html/template

libraries:
- name: webapp2
  version: "2.5.2"
